confdir = "/etc/confd"
log-level = "debug"
interval = 600
noop = false

[[backend]]
id = "default"
type = "env"
client_cert = "/etc/confd/ssl/client.crt"
client_key = "/etc/confd/ssl/client.key"
nodes = [
  "http://127.0.0.1:4001",
]
prefix = "/production"
scheme = "https"
srv_domain = "etcd.example.com"

[[backend]]
id = "env_vars"
type = "env"
prefix = "/production"
